name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust nightly
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly -y
        source $HOME/.cargo/env
    - name: Install clang-sys Dependencies
      run: sudo apt-get install -y clang llvm lld libclang-dev
    - name: Build
      run: cargo build --all-features --verbose
